---
title: ""
output:
  pdf_document:
    template: template-alt.tex
---

<!--
# Some Simple Examples

## One-line equation

Euler's constant: $e = \mathop {\lim }\limits_{n \to \infty } \left( {1 + \frac{1}{n}} \right)^n$

## Multi-line equation

This renders as a "pop-up" in Rstudio if you've selected "Inline" with the "Show equation and image previews" option at Tools > Global Options... > Rmarkdown

$$
\begin{array}{lcl}
I &=& \int (x + 1) dx \\
&=& \frac{x^2}{2} + x + C.
\end{array}
$$

## Comments with `\iffalse` (and closing `\fi`)

You shouldn't see anything in the output PDF here (although there is an equation in the Rmarkdown document).

\iffalse
Integration by parts: $\int {u\frac{{dv}}{{dx}}} dx = uv - \int {\frac{{du}}{{dx}}} vdx$
\fi

# A "Big" Test of Equations

**Source:** [Griffith Quantum Mechanics Time Dependent Perturbation theory CheatSheet (UCB 137B final) on www.overleaf.com](https://www.overleaf.com/articles/griffith-quantum-mechanics-time-dependent-perturbation-theory-cheatsheet-ucb-137b-final/jwynrzctvqgp)
-->



# Investment Strategy Development

---

## Computing Returns

---

### ordinary return:

\begin{equation}
R_{n, t}=\frac{P_{n, t}+D_{n, t}}{P_{n, t-1}}-1
\end{equation}

### log return: 

\begin{equation}
\begin{aligned} r_{n, t}=\ln \left(\frac{P_{n, t}+D_{n, t}}{P_{n, t-1}}\right)=\ln \left(1+R_{n, t}\right) \end{aligned}
\end{equation}

### cumulative returns:

\begin{equation}
\begin{aligned} V_{T} &=V_{0} \prod_{t=1}^{T}\left(1+R_{t}\right) \\ &=V_{0} \exp \left(\sum_{t=1}^{T} r_{t}\right) \end{aligned}
\end{equation}

\begin{equation}
\begin{aligned}
R_{0, T} &=\frac{V_{T}}{V_{0}}-1=\prod_{t=1}^{T}\left(1+R_{t}\right)-1 \neq \sum_{t=1}^{T} R_{t} \\
r_{0, T} &=\ln \left(\frac{V_{T}}{V_{0}}\right)=\sum_{t=1}^{T} r_{t}
\end{aligned}
\end{equation}

### average ordinary returns per period:

\begin{equation}
\begin{aligned}
\bar{R}_{0, T}=\left(\frac{V_{T}}{V_{0}}\right)^{\frac{1}{T}}-1=\left(\prod_{t=1}^{T}\left(1+R_{t}\right)\right)^{\frac{1}{T}}-1
\end{aligned}
\end{equation}

### average log returns per period:

\begin{equation}
\bar{r}_{0, T}=\frac{1}{T} \ln \left(\frac{V_{T}}{V_{0}}\right)=\frac{1}{T} \sum_{t=1}^{T} r_{t}
\end{equation}

\begin{equation}
\begin{aligned}
&\text {Assessing Profitability:}\\
&\begin{array}{lcc}
\hline \text {one-period return} \\
\text {that is zero}
& \begin{array}{c}
\text { Profit over } \\
\text { one period }
\end{array} & \begin{array}{c}
\text { Profit over } \\
\text { mult. periods }
\end{array} \\
\hline \text {arith. av realized r} & 0 & - \\
\text {geom. av realized r} & 0 & 0 \\
\text {arith. av realized log r} & 0 & 0 \\
\hline \text {expected r}^* & 0 & 0 \\
\text {expected log r}^{**} & + & + \\
\hline
\end{array}
\end{aligned}
\end{equation}

\begin{equation}
\begin{aligned}
^*: E[(1+R_1)(1+R_2)] &= 1+ E(R_1) + E(R_2) + E(R_1R_2)\\
^**: E(exp(r)) &\geq exp(E(r)), \text{because of convexity}
\end{aligned}
\end{equation}

### Time Scaling:

\begin{equation}
\begin{aligned}
\bar{R}_{0, T}^{\text {annual }}&=\left(\prod_{t=1}^{T}\left(1+R_{t}\right)\right)^{\frac{m}{T}}-1 \\
\bar{r}_{0, T}^{\text {annual }}&=\frac{m}{T} \sum_{t=1}^{T} r_{t}
\end{aligned}
\end{equation}

### Portfolio Returns

\begin{equation}
\begin{aligned}
R_{p, t+1} &=\sum_{n=1}^{N} w_{n, t} R_{n, t+1}=\mathbf{w}_{t}^{\prime} \mathbf{R}_{t+1} \\
r_{p, t+1} &=\ln \left(1+R_{p, t+1}\right)
\end{aligned}
\end{equation}

Ordinary returns aggregate in the cross-section, log returns not.

* ordinary returns for one-period returns.  
* log returns for multiple-period returns.  

If the riskless assset is **asset 0**:

\begin{equation}
R_{p, t+1}=\mathbf{w}_{t}^{\prime} \mathbf{R}_{t+1}+\left(1-\mathbf{w}_{t}^{\prime} \mathbf{1}\right) R_{f, t+1}
\end{equation}

###  Returns on Long-Short Portfolios

\begin{equation}
\begin{aligned}
w_t &= \text{\% position in the different assets} \\
L_{n,t+1} &= \text{\% stock lending fee from t to t+1} \\
\bar{L} &= \text{average lending fee}
\end{aligned}
\end{equation}

\begin{equation}
\begin{aligned}
R_{p, t+1}&=\mathbf{w}_{t}^{\prime} \mathbf{R}_{t+1}+\left(1-\mathbf{w}_{t}^{\prime} \mathbf{1}\right) R_{f, t+1}+ \sum_{n=1}^{N} \min \left[w_{n, t}, 0\right] L_{n, t+1} \\
R_{p, t+1}&=\mathbf{w}_{t}^{\prime} \mathbf{R}_{t+1}+\left(1-\mathbf{w}_{t}^{\prime} \mathbf{1}\right) R_{f, t+1}+\bar{L} \sum_{n=1}^{N} \min \left[w_{n, t}, 0\right]
\end{aligned}
\end{equation}

###  Returns on Zero-Cost Long-Short Portfolios

\

Keep track of the long and short legs separately and **require the weights of each to sum to one**.

\

\begin{equation}
\begin{aligned}
w_L &= \text{portfolio held long} \\
w_s &= \text{portfolio held short}
\end{aligned}
\end{equation}

Returns on each leg

\begin{equation}
\begin{array}{l}
R_{p, t+1}^{L}=\mathbf{w}_{L}^{\prime} \mathbf{R}_{t+1} \\
R_{p, t+1}^{S}=\mathbf{w}_{S}^{\prime}\left(\mathbf{R}_{t+1}+\mathbf{L}_{t+1}\right)
\end{array}
\end{equation}

\
Return on the zero-cost long-short portfolio (**excess return**)

\begin{equation}
R_{p, t+1}=R_{p, t+1}^{L}-R_{p, t+1}^{S}=\mathbf{w}_{L}^{\prime} \mathbf{R}_{t+1}-\mathbf{w}_{S}^{\prime}\left(\mathbf{R}_{t+1}+\mathbf{L}_{t+1}\right)
\end{equation}

\
Return on the zero-cost long-short portfolio (**raw return**)

\begin{equation}
R_{p, t+1}=R_{p, t+1}^{L}-R_{p, t+1}^{S} + R_{f,t+1}
\end{equation}


###  Accounting for Dividends and Interest: Witholding Taxes

\begin{equation}
\begin{aligned}
V_t &= \text{Value of the portfolio before any taxes} \\
D_t &= \text{aggregate dividends paid on long positions} \\
\tau_d &= \text{domestic tax rate}\\
\tau_f &= \text{nonrefundable part of the foreign withholding tax rate}
\end{aligned}
\end{equation}

\begin{equation}
\begin{array}{lr}
\hline \text {wh. tax on long D} & \tau_{f} D_{t} \\
\text {Tax credit } & -\min \left(\tau_{f}, \tau_{d}\right) D_{t} \\
\text {Dom. income tax } & \tau_{d}\left(V_{t}-V_{t-1}\right) \\
\hline \text { Total tax cost } & \tau_{d}\left(V_{t}-V_{t-1}\right)+\max \left(\tau_{f}-\tau_{d}, 0\right) D_{t} \\
\hline
\end{array}
\end{equation}

Expressed in terms of returns, the tax is:

\begin{equation}
\frac{\text{total tax cost}}{V_{t-1}}=\tau_{d} R_{p, t}+\max \left(\tau_{f}-\tau_{d}, 0\right) \frac{D_{t}}{V_{t-1}}
\end{equation}

and the after-tax return is:

\begin{equation}
R_{p, t}^{net}= R_{p, t} (1-\tau_{d}) - \max \left(\tau_{f}-\tau_{d}, 0\right) \frac{D_{t}}{V_{t-1}}
\end{equation}

###  Portfolios with Futures Contracts

\begin{equation}
\begin{aligned}
R_{p,t+1} &= \text{portfolio return excluding futures} \\
R_{p,t+1}^{F} &= \text{portfolio return with futures} \\
F_t &= \text{futures price} \\
N_F &= \text{portfolio's futures exposure}\\
&= \text{number of contracts times multiplier}
\end{aligned}
\end{equation}

The change in the total value of the portfolio $V_t$ is:

\begin{equation}
V_{t+1}-V_{t}=V_{t} R_{p, t+1}+N_{F, t}\left(F_{t+1}-F_{t}\right)
\end{equation}

The percentage return on the portfolio with futures is:

\begin{equation}
\begin{aligned}
R_{p, t+1}^{F}&=\frac{V_{t+1}}{V_{t}}-1=R_{p, t+1}+\frac{N_{F, t} F_{t}}{V_{t}} \frac{F_{t+1}-F_{t}}{F_{t}} \\
&=R_{p, t+1}+w_{F, t} R_{F, t+1}
\end{aligned}
\end{equation}

Hence, the return on a portfolio comprising futures can be computed as usual. The difference is that the weights need not sum to one.

\

### Relation between Index and Futures Returns

\

Absent market frictions, **futures returns equal index returns including dividends minus the riskless rate**.
$\to$ In periods with high interest rates, the index does better than the futures. Intuition: By investing in futures, I have the same risk as by investing in the index, but I don't have to invest the money $\to$ subtract the interest rate.

\

\begin{equation}
\begin{aligned}
dB_t &= \text{a Brownian motion increment} \\
\mu_t &= \text{drift} \\
\sigma_t &= \text{volatility} \\
r &= \text{riskless rate} \\
T &= \text{maturity}
\end{aligned}
\end{equation}

Proof: 

Suppose that the value of the underlying **price index** follows:

\begin{equation}
d S_{t}=\left(\mu_{t}-q\right) S_{t} d t+\sigma_{t} S_{t} d B_{t}
\end{equation}

The price of a futures contract maturing at T is:

\begin{equation}
F_{t}= S_{t} e^{(r-q)(T-t)}.
\end{equation}

Using the Ito formula, the **return on the futures contract is**:

\begin{equation}
\begin{aligned}
d F_{t}&=d S_{t} e^{(r-q)(T-t)}-S_{t}(r-q) e^{(r-q)(T-t)} d t \\
&=\frac{d S_{t}}{S_{t}} F_{t}-(r-q) F_{t} d t
\end{aligned}
\end{equation}

This can be rewritten as:

\begin{equation}
\begin{aligned}
\frac{d F_{t}}{F_t}= \frac{d S_{t}}{S_{t}} -(r-q) d t = \left(\mu_{t}-q\right)d t+\sigma_{t} d B_{t}
\end{aligned}
\end{equation}

For a **total return index** one has:

\begin{equation}
d S_{t}=\mu_{t} S_{t} d t+\sigma_{t} S_{t} d B_{t}
\end{equation}

and

\begin{equation}
F_{t}= S_{t} e^{r(T-t)}.
\end{equation}

The expression for the futures return does not change.

\

---

## Performance Measurement

---

### Computing Excess Returns

\

Only subtract the riskless rate $R_f$, if the portfolio has to be funded: 
\begin{equation}
\begin{array}{lc}
\hline \text {Type of portfolio } & \text { Subtract } R_{f} ? \\
\hline \text {Long-only portfolio of funded positions} & \text { Yes } \\
\text {(stocks, bonds, ETFs, options) } & \\
\text {Zero-cost long-short portfolio } & \text { No } \\
\text {Futures or forward contracts, long or short } & \text { No } \\
\hline
\end{array}
\end{equation}

Intermediate cases are not typical but possible. For example, if the portfolio buys stocks for 100\%, shorts bonds for 40% and buys futures for 30\%, one should subtract 60\% of the riskless rate from the returns.

\

### Sharpe ratio

\

It gives the average return achieved by a portfolio in excess of the risk-free rate,$R_p-R_f$ , per unit of **total portfolio risk** $\sigma_p$:

\begin{equation}
SR_p= \frac{R_p-R_f}{\sigma_p}
\end{equation}

$\bigoplus$: Its computation does not require a benchmark portfolio. \
$\pmb{\circleddash}$: It does not distinguish whether the returns are generated by taking systematic or idiosyncratic risk.\
$\pmb{\circleddash}$: It only considers the first two moments of the return distribution (mean \& variance).

\

### Alpha

\

A portfolio's alpha is the excess return on the portfolio over the return that would have been achieved by investing in a benchmark portfolio that has the same systematic risk. 

\begin{equation}
\begin{aligned}
R_{j,t}= \text{excess returns on (portfolios of) } \textbf{traded assets}
\end{aligned}
\end{equation}

\begin{equation}
R_{p, t}-R_{f, t}=\alpha_{p}+\sum_{j=1}^{J} \beta_{j} R_{j, t}+\varepsilon_{p, t}
\end{equation}


### Benchmark models

\

#### The Market Model:

\begin{equation}
\begin{aligned}
R_{p, t}-R_{f, t}=\alpha_{p}+\beta_{p}\left(R_{M, t}-R_{f, t}\right)+\varepsilon_{p, t}
\end{aligned}
\end{equation}

#### The Fama-French 3-Factor Model:

\begin{equation}
\begin{aligned}
R_{p, t}-R_{f, t}=& \alpha_{p}+\beta_{M, p}\left(R_{M, t}-R_{f, t}\right)+\beta_{S M B, p}\left(R_{S, t}-R_{B, t}\right) \\
&+\beta_{H M L, p}\left(R_{H, t}-R_{L, t}\right)+\varepsilon_{p, t}
\end{aligned}
\end{equation}

#### The Fama-French-Carhart 4-Factor Model:
\begin{equation}
\begin{aligned}
R_{p, t}-R_{f, t}=& \alpha_{p}+\beta_{M, p}\left(R_{M, t}-R_{f, t}\right)+\beta_{S M B, p}\left(R_{S, t}-R_{B, t}\right) \\
&+\beta_{H M L, p}\left(R_{H, t}-R_{L, t}\right) \\
&+\beta U_{M D, p}\left(R_{U, t}-R_{D, t}\right)+\varepsilon_{p, t}
\end{aligned}
\end{equation}

#### The Fung-Hsieh Model:
\begin{equation}
\begin{aligned}
R_{p, t}-R_{f, t}=& \alpha_{p}+\beta_{M, p}\left(R_{M, t}-R_{f, t}\right)+\beta_{S M B, p}\left(R_{S, t}-R_{B, t}\right) \\
&+\beta_{\text {Term}, p}\left(R_{\text {10yTry }, t}-R_{f, t}\right) \\
&+\beta_{\text {Default}, p}\left(R_{\text {BAA}, t}-R_{\text {10yTry }, t}\right) \\
&+\beta_{\text {FX}, p}\left(R_{\text {FXStraddle}, t}-R_{f, t}\right) \\
&+\beta_{\text {Cdty}, p}\left(R_{\text {CdtyStraddle}, t}-R_{f, t}\right) \\
&+\beta_{\text {Bond}, p}\left(R_{\text {BondStraddle}, t}-R_{f, t}\right)+\varepsilon_{p, t}
\end{aligned}
\end{equation}

\

### Measuring Timing Ability 

\

#### 1. Plotting Beta against Market Return

If the strategy is successful at timing the market, there should be a positive relation between the $\beta$ (return on the asset class / exposure to a specific factor) of the portfolio and the market return (or the difference between the market return and the bond return).

\

#### 2. Comparing Portfolio Return and Market Return

If the strategy is successful at timing the market, the portfolio's exposure to fluctuations in the market is greater when the market goes up than when it goes down. This yields a convex relation between the market return and the return on the portfolio.

\

#### Treynor/Mazuy procedure
is to fit a quadratic curve to the performance data, i.e. run the (linear) regression

\begin{equation}
R_{p, t}-R_{f, t}=\alpha_{p}+\beta_{p}\left(R_{M, t}-R_{f, t}\right)+\gamma_{p}\left(R_{M, t}-R_{f, t}\right)^{2}+\varepsilon_{p, t} 
\end{equation}

\

#### Merton/Henriksson procedure
is to recognize that the portfolio return in the timing case is similar to the payoff diagram of a long market plus call on the market position and to run the regression

\begin{equation}
\begin{aligned}
R_{p, t}-R_{f, t}=&\alpha_{p}+\beta_{p}\left(R_{M, t}-R_{f, t}\right) \\
&+\gamma_{p} \max \left(R_{M, t}-R_{f, t}, 0\right) +\varepsilon_{p, t}
\end{aligned}
\end{equation}

There is evidence of timing ability if the coefficient $\gamma_p$ is positive (and statistically significant). Unfortunately, the power of these tests is low.

\

\- Note that $\alpha_p$ and $\beta_p$ will be distorted if the strategy involves timing but timing is not modeled explicitly when trying to measure performance. (Two subperiod relations are then estimated as one fitted linear relation.)

***

## Principles of Strategy Development
***

### Bible on One Page

\

#### 1. Always worry about statistical significance

\- When assessing significance, beware of nonspherical residuals, overlapping returns, and persistent predictors.

#### 2. Beware of overfitting / data mining:

\- If you make numerous trials you'll end up getting something that looks signifcant even though there is nothing. \
\- If you develop a timing model that recommends few switches you might be overfitting the data. (This is generally due to persistent predictors.)

#### 3. Beware of biases: \

\- **Look-ahead bias**: Make sure that your strategy only uses data that was available at the time the investment decision had to be made.\
\- **Selection bias**: Is your sample a random/representative draw? \
\- **Backfilling bias**: Was data backfilled in the database you are using?

#### 4. Account for transaction costs.

#### 5. Implement what you tested.

\

### Statistical Significance

\

#### 1. Nonnormality:
Returns on many assets are not normally distributed \
$\to$ **Nonnormal Residuals**: By the Gauss-Markov theorem, the OLS estimator is the best linear unbiased estimator (BLUE) if the errors are IID. Normality is not required.

#### 2. Nonspherical Residuals: 
Volatility is time-varying so asset returns are not IID. \
$\to$ **Non-IID Residuals (correlated or heteroskedastic)**: \
\- The **OLS estimator is still unbiased** (but inefficient; the GLS estimator is BLUE in this case; in effect GLS transforms the errors to make them uncorrelated and homoskedastic). \
\- However, the **OLS standard errors are incorrect**. To assess the sampling variance of the estimates, you should use robust standard errors.

\

### Avoiding Overfitting

\

\- Keep the number of trials low. \
\- Keep the strategy relatively simple: If your strategy is a simple "if-else", you are less likely to be overfitting than if it involves many layers of nested ifs. \
\- **Run out-of-sample tests**: Split the data in two pieces. One is used to develop the strategy, the other to perform an out-of-sample test of its performance. \
\- Investigate the robustness of the strategy to changes in parameters

\

### Avoiding Biases

\

#### Look-ahead Bias

\

Arises if a strategy makes use of information that was not actually available at the time the investment decision was made. \
**Make sure that the value of $x_t$ was really known at time t**. Note that it is not sufficient that $x_t$ relates to period t. \
**Make sure you estimate the regression coefficients using only data through period t**. If you estimate them using data through the end of your sample they actually include information about the future.
\begin{equation}
R_{t+1} = \alpha + \beta x_t + \varepsilon_{t+1}
\end{equation}

Typical Problem Cases:

\
\- Accounting data gets published with a lag of several months. \
\- Some financial market data (e.g. open interest, mutual fund NAV) gets published with a lag of one trading day. \
\- Time zones. US markets close after Asian markets. So the US return for the day is not known when Japan closes, and you can't use it to decide whether to invest in Japanese stocks at the close of that day. \
\- Data revisions.

\

#### Selection Bias

\

Arises when the sample is not a random draw from the underlying population, causing assets with certain characteristics to be over- or under-represented in the sample. \

**Fix**: If possible, use the entire population instead of a sample.

\

#### Survivorship Bias

\

Is a **form of selection bias** that arises when the sample used in the analysis only includes assets that are still traded at the end of the sample period. 

\

Examples: 

\
\- You backtest a strategy using the current members of a stock market index. In doing so you leave out firms that left the index in previous years.
\- You backtest a strategy using bonds that are traded at the end of your sample period. In doing so you leave out the ones that matured and the ones that defaulted.
\- You backtest a strategy using commodities for which futures contracts currently exist. In doing so you leave out contracts that were delisted.

**Fix**:

\
\- Using the population of all assets in a given category as universe, or  
\- Using the constituents of an index at a time preceding each investment decision as universe.

\

#### Backfilling Bias / Instant History Bias

\

Arises if historical data is backfilled into a database when an asset is added to it.

\

**Fix**: Provided that the database contains information on the effective inclusion date, drop data for the assets before their inclusion date.

\

### Accounting for Transaction Costs  

\
  
#### Proportional Transaction Costs
Let c denote the trading cost per currency unit (including commissions, the bid-ask spread, and any transaction taxes).  

\

A rough estimate of the effect of transaction costs on the return per period is just the product of c and the strategy's average turnover. For example, if transaction costs are c = 0.2% and the strategy's turnover is 250% per year, transaction costs will reduce returns by about 0.5% per year.

\

# Bonds / Interest Rates

---

## Definitions and Notations

---

\begin{equation}
\begin{aligned}
P_{t}^{(n)} &= \text{price of a n-year discount bond at time t} \\
p_{t}^{(n)} &= \text{corresponding log bond price} \\
Y_{t}^{(n)} &= \text{gross yield on a discount bond with n years to maturity} \\
y_{t}^{(n)} &= \text{log yield of a n-year discount bond at time t} \\
y_{t}^{(1)} &= \text{short rate} \\
y_{t}^{(n)} &= \text{long rate} \\
f_t^{(n)} &-y_t^{(1)} =  \text{forward spot spread}
\end{aligned}
\end{equation}

### Bond Prices and Yields

\begin{equation}
\begin{aligned}
P_{t}^{(n)}&=\frac{1}{\left(Y_{t}^{(n)}\right)^{n}} \\
p_{t}^{(n)}&=-ny_{t}^{(n)} \\
Y_{t}^{(n)}&=\left(\frac{1}{P_{t}^{(n)}}\right)^{\frac{1}{n}} \\
y_{t}^{(n)}&=-\frac{1}{n} p_{t}^{(n)}=\ln \left(Y_{t}^{(n)}\right)
\end{aligned}
\end{equation}

### Forward Rates  

\

The forward rate is the rate at which you can contract today to lend or borrow in the future. We denote the discrete and continuously compounded forward rates for a loan from time $t+n-1$ to time $t + n$ by $F_{t}^{(n)}$ and $f_{t}^{(n)}$, respectively.  

- No arbitrage implies that

\begin{equation}
\begin{aligned}
F_{t}^{(n)}&=\frac{P_{t}^{(n-1)}}{P_{t}^{(n)}} \\
f_{t}^{(n)}&=p_{t}^{(n-1)}-p_{t}^{(n)} \\
\end{aligned}
\end{equation}

- Bond prices can be expressed as their discounted present value using forward rates:

\begin{equation}
\begin{aligned}
P_{t}^{(n)}&=\left(\prod_{j=1}^{n} F_{t}^{j}\right)^{-1} \\
p_{t}^{(n)}&=-\sum_{j=1}^{n} f_{t}^{j}
\end{aligned}
\end{equation}

### Returns

\

The **returns from holding a n-period bond** from time $t$ to time $t + 1$ are:

\begin{equation}
\begin{aligned}
R_{t+1}^{(n)} &=\frac{P_{t+1}^{(n-1)}}{P_{t}^{(n)}} \\
r_{t+1}^{(n)} &=p_{t+1}^{(n-1)}-p_{t}^{(n)} \\
\end{aligned}
\end{equation}

The **return from holding a one-period bond** is just its yield, i.e.

\begin{equation}
\begin{aligned}
R_{t+1}^{(1)} &=Y_{t}^{(1)} \\
r_{t+1}^{(1)} &=y_{t}^{(1)}
\end{aligned}
\end{equation}

The **excess log returns** from holding an n-period bond are

\begin{equation}
\begin{aligned}
r x_{t+1}^{(n)}=r_{t+1}^{(n)}-y_{t}^{(1)}
\end{aligned}
\end{equation}

**Decomposition of the excess log returns** into the **initial yield spread** and the **change in the bond's log yield** from period $t$ to period $t + 1$ **scaled by its (remaining) duration**:

\begin{equation}
\begin{aligned}
r x_{t+1}^{(n)}&=r_{t+1}^{(n)}-y_{t}^{(1)} \\
&=p_{t+1}^{(n-1)}-p_{t}^{(n)}-y_{t}^{(1)} \\
&=-(n-1) y_{t+1}^{(n-1)}+n y_{t}^{(n)}-y_{t}^{(1)} \\
&=\underbrace{\left(y_{t}^{(n)}-y_{t}^{(1)}\right)}_{\text {Initial yield spread }}-\underbrace{(n-1)}_{\text {Duration }} \underbrace{\left(y_{t+1}^{(n-1)}-y_{t}^{(n)}\right)}_{\text {Yield change }}
\end{aligned}
\end{equation}

\

## Three Basic Questions

\

### 1. Why do interest rates move?  

- Yields are characterized by a dominant level factor shifting yields of all maturities up and down.
- The short rates are set by the central bank taking macroeconomic factors such as unemployment and expected inflation into account.

### 2. Why do yields differ across maturities?  

- The **yield curve** is a plot of yields of zero-coupon bonds as a function of their maturity. It is also called the **term structure of interest rates**.

- The level and shape of the yield curve vary over time depending on economic conditions.

### 3. Why does the yield spread vary over time?

- The **yield spread** (also called the term spread or term premium) represents the **slope of the yield curve**.

- During recessions, the yield curve steepens, while during expansions it flattens or sometimes even inverts.

- Yield curve inversions tend to occur **right before recessions**.

\ 

## The Expectations Hypothesis 

\

Under the expectations hypothesis, **risk premia are constant and unpredictable**.

\

**rpy** is the expected return from holding a n-period bond to maturity, financed by rolling over short-term bonds.  

**rpf** (or forward premium) is the expected return from planning to borrow for a year in the future spot market and agreeing today to lend in the forward market.  

**rph** is the one-period excess return from holding a long-term bond for one period, financed by issuing a one-period bond. This is typically the dependent variable in return predictability regressions.  

\

Alternative ways of getting money from one period to another must have the same expected value (plus a risk premium).

- The **n-period yield** is the **average of expected future one-period yields**:

\begin{equation}
\begin{aligned}
y_{t}^{(n)}=\frac{1}{n} \mathbb{E}_{t}\left[y_{t}^{(1)}+y_{t+1}^{(1)}+\ldots+y_{t+n-1}^{(1)}\right]+r p y^{(n)}
\end{aligned}
\end{equation}

- The **forward rate** equals the **expected future spot rate**:

\begin{equation}
\begin{aligned}
f_{t}^{(n)}=\mathbb{E}_{t}\left[y_{t+n-1}^{(1)}\right]+r p f^{(n)}
\end{aligned}
\end{equation}

- The **expected returns** from holding bonds (for one year!!) of **all maturities** are **identical**:

\begin{equation}
\begin{aligned}
\mathbb{E}_{t}\left[r_{t+1}^{(n)}\right]=y_{t}^{(1)}+r p h^{(n)}
\end{aligned}
\end{equation}

In the purest form of the expectations hypothesis, $rpy$, $rpf$ and $rph$ are zero.

\

## Bond Risk Premium

\

### Empirical Evidence

\

\- **Long term bonds are heavily overpriced**. $\to$ average holding period returns of bonds of different maturities are quite similar, despite the increasing standard deviation of longer-maturity bond returns.  
\- **The reward for extending the duration** is highest at short maturities and decays at longer maturities.  
\- The **Sharpe ratios obtained by extending the duration** exceed **one at short maturities** (if the one-month Treasury bill is used as the riskless rate) and decline monotonically from the shortest to the longest portfolios.

\

## Predictability

\

### Basic Idea  

\

**Under the expectations hypothesis, risk premia are constant and unpredictable.**

\

### Testing the **EH** Using **Forward-Spot Spreads**

\

**Form 2**: Forward rates should forecast future short rates:

\begin{equation}
\begin{aligned}
f_{t}^{(n)}=\mathbb{E}_{t}\left[y_{t+n-1}^{(1)}\right]+r p f^{(n)} \\
\end{aligned}
\end{equation}

Implied regression:

\begin{equation}
\begin{aligned}
y_{t+n-1}^{(1)}=\alpha+\beta f_{t}^{(n)}+\varepsilon_{t+n-1} \\
\end{aligned}
\end{equation}

The **EH predicts that $\beta=1$.**  

\

Since interest rates are very persistent, it is better to use spreads instead (substract $y_{t}^{(1)}$ to make variables stationary):
\begin{boldmath}
\begin{equation}
\begin{aligned}
y_{t+n-1}^{(1)}-y_{t}^{(1)}=\alpha+\beta\left(f_{t}^{(n)}-y_{t}^{(1)}\right)+\varepsilon_{t+n-1}
\end{aligned}
\end{equation}
\end{boldmath}

Under the EH, the spread between the forward 1-year rate and today's 1-year rate should predict the change in the 1-year yield over the next $n-1$ years.

\

#### Fama-Bliss Regressions

\

Decompose the forward-spot $f_{t}^{(n)}-y_{t}^{(1)}$ spread into an entity that has to **hold ex ante and ex post**.

\begin{equation}
\begin{aligned}
f_{t}^{(n)}-y_{t}^{(1)} &=p_{t}^{(n-1)}-p_{t}^{(n)}-y_{t}^{(1)} \\
&=\left(p_{t+1}^{(n-1)}-p_{t}^{(n)}-y_{t}^{(1)}\right)+\left(-p_{t+1}^{(n-1)}+p_{t}^{(n-1)}\right) \\
&= \underbrace{\left(r_{t+1}^{(n)}-y_{t}^{(1)}\right)}_{\text {excess return }} + \underbrace{(n-1)\left(y_{t+1}^{(n-1)}-y_{t}^{(n-1)}\right)}_{\text {changes in yields }}
\end{aligned}
\end{equation}

\

The **forward-spot spread** must **predict future returns** or **changes in yields**.

\

Regressions:
\begin{boldmath}
\begin{equation}
\begin{array}{c}
y_{t+n-1}^{(1)}-y_{t}^{(1)}=\alpha+\beta\left(f_{t}^{(n)}-y_{t}^{(1)}\right)+\varepsilon_{t+n-1} \\
r_{t+1}^{(n)}-y_{t}^{(1)}=a+b\left(f_{t}^{(n)}-y_{t}^{(1)}\right)+\eta_{t+1}
\end{array}
\end{equation}
\end{boldmath}
Under the **EH**:

- Forward rates forecast future short rates $\pmb{(\beta=1)}$
- Risk premia are constant and unpredictable $\pmb{(b=0)}$  

# Currencies

\

## Measuring Returns on FX Investments

\

\begin{equation}
\begin{aligned}
R_{t,k} &= \text{return on foreign asset measured in domestic currency} \\
r_{t,k} &= ln(1+R_{t,k}) \\
R_{t,k}^{FX} &= \text{currency return measured in domestic currency} \\
R_{t,k}^{*} &= \text{return on foreign asset measured in foreign currency} \\
r_{t,k}^{*} &= ln(1+R_{t,k}^{*}) \\
S_t &= \text{spot exchange rate expressed as $\frac{dom. curr}{for. curr.}$} \\
s_t &= ln(1+R_{t,k}^{*}) \\
\end{aligned}
\end{equation}

\

The **Gross Return** measured in **domestic currency** is
\begin{equation}
\begin{aligned}
\pmb{1+R_{t, k}}&=V_{t+k}=\frac{S_{t+k}\left(1+R_{t, k}^{*}\right)}{S_{t}} \\
&=\underbrace{\left(1+R_{t, k}^{F \chi}\right)}_{\text {return on $\Delta{S}$ }}\underbrace{\left(1+R_{t,k}^{*}\right)}_{\text { return on for. currency}}\\
\pmb{r_{t, k}}&=s_{t+k}-s_{t}+r_{t, k}^{*}=r_{t, k}^{F X}+r_{t, k}^{*} \\
\end{aligned}
\end{equation}


**Excess Log Return** compared to domestic riskless asset $\pmb{i_{t,k}}$:

\begin{equation}
\begin{array}{l}
\pmb{r x_{t, k}}=s_{t+k}-s_{t}+r_{t, k}^{*}-i_{t, k}
\end{array}
\end{equation}

## Covered Interest Rate Parity (CIP)

\begin{equation}
\begin{aligned}
I_{t,k} = &\text{ k-period cumulative discrete interest (with compounding)} \\
&\text{ earned on the domestic currency at time t} \\
i_{t,k} = &\text{ }ln(1+I_{t,k}) \\
I_{t,k}^{*} = &\text{ k-period cumulative discrete interest (with compounding)} \\
&\text{ earned on the foreign currency at time t} \\
i_{t,k}^{*} = &\text{ }ln(1+I_{t,k}^{*}) \\
F_{t,k} = &\text{ forward foreign exchange rate}
\end{aligned}
\end{equation}

Note: the forward foreign exchange rate is the FX rate you can agree to today for a foreign currency transaction with delivery in k periods. If you sell the foreign currency forward, you will receive $F_{t,k}$ units of the domestic currency per unit of foreign currency at time t + k.

